-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Aug 28, 2023 at 01:48 PM
-- Server version: 10.4.28-MariaDB
-- PHP Version: 8.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `news`
--

-- --------------------------------------------------------

--
-- Table structure for table `tbl_article`
--

CREATE TABLE `tbl_article` (
  `id` int(10) NOT NULL,
  `title` varchar(255) DEFAULT NULL,
  `image` varchar(255) DEFAULT NULL,
  `description` text DEFAULT NULL,
  `likes` varchar(255) DEFAULT NULL,
  `dislikes` varchar(255) DEFAULT NULL,
  `views` varchar(255) NOT NULL,
  `created_at` datetime DEFAULT NULL,
  `related_articles` varchar(255) DEFAULT NULL,
  `source` varchar(255) DEFAULT NULL,
  `author` varchar(255) DEFAULT NULL,
  `category` varchar(255) DEFAULT NULL,
  `url` varchar(255) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `tbl_article`
--

INSERT INTO `tbl_article` (`id`, `title`, `image`, `description`, `likes`, `dislikes`, `views`, `created_at`, `related_articles`, `source`, `author`, `category`, `url`) VALUES
(1, 'This Evil Stepmother Has Perfect Comedic Timing', 'https://static01.nyt.com/images/2023/08/17/multimedia/15SIMARD-01-bwmg/15SIMARD-01-bwmg-moth.jpg', 'In “Once Upon a One More Time,” Jennifer Simard finds value in seeing “how small you can make something and achieve a big result.”', '22', '7', '0', '2023-08-16 18:50:19', '1,2,4,5', 'The New York Times', 'Juan A. Ramírez', 'entertainment', 'https://www.nytimes.com/2023/08/16/theater/jennifer-simard-once-upon-a-one-more-time.html'),
(2, 'Schumer and McCarthy Agree Stopgap Spending Bill Necessary to Avoid Shutdown', 'https://static01.nyt.com/images/2023/08/16/multimedia/16dc-spending-tvcm/16dc-spending-tvcm-moth.jpg', 'The Senate majority leader said his meeting with Speaker Kevin McCarthy to agree to support a resolution that would extend funding for a few months was “a good sign.”', '1', '1', '1', '2023-08-16 18:44:17', '1,2,4,5', 'The New York Times', 'Annie Karni', 'politics', 'https://www.nytimes.com/2023/08/16/us/politics/schumer-mccarthy-stopgap-spending-shutdown.html'),
(3, 'Minister grijpt in om nieuwe vertraging uitrol 5G te voorkomen', 'https://www.telegraaf.nl/images/1200x630/filters:format(jpeg):quality(80)/cdn-kiosk-api.telegraaf.nl/c24a7e0c-3c64-11ee-965d-02c309bc01c1.jpg', 'Door een slepende ruzie met een satellietbedrijf dreigt opnieuw vertraging bij de uitrol van supersnel mobiel internet (5G) in Nederland. Om dat te voorkomen, pakt minister Micky Adriaansens (Economische Zaken) de frequentie van het bedrijf af.', '1', '1', '7', '2023-08-16 18:43:14', '1,2,4,5', 'De Telegraaf - Financieel Overzicht', NULL, 'business', 'https://www.telegraaf.nl/financieel/49939303/minister-grijpt-in-om-nieuwe-vertraging-uitrol-5-g-te-voorkomen?utm_source=RSS&utm_medium=RSS'),
(4, 'Historians and literary scholars tackle the Shakespeare authorship question', 'https://scx1.b-cdn.net/csz/news/tmb/2023/shakespeare-1.jpg', 'The Journal of Scientific Exploration (JSE), an open access journal, has published its summer issue, which is specially devoted to what is known as the Shakespeare authorship question (SAQ).', '1', '1', '0', '2023-08-16 18:38:07', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-historians-literary-scholars-tackle-shakespeare.html'),
(5, 'Microplastic pollution: New device uses wood dust to trap up to 99.9% of microplastics in water', 'https://scx1.b-cdn.net/csz/news/tmb/2023/microplastic-pollution.jpg', 'Could plants be the answer to the looming threat of microplastic pollution? Scientists at UBC\'s BioProducts Institute found that if you add tannins—natural plant compounds that make your mouth pucker if you bite into an unripe fruit—to a layer of wood dust, you can create a filter that traps virtually all microplastic particles present in water.', '1', '1', '0', '2023-08-16 18:38:02', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-microplastic-pollution-device-wood-microplastics.html'),
(6, 'Researchers achieve high-speed super-resolution imaging with a large field of view', 'https://scx1.b-cdn.net/csz/news/tmb/2023/researchers-achieve-hi-2.jpg', 'Researchers have developed a fluorescence microscope that uses structured illumination for fast super-resolution imaging over a wide field of view. The new microscope was designed to image multiple living cells simultaneously with a very high resolution to study the effects of various drugs and mixtures of drugs on the body.', '1', '1', '0', '2023-08-16 18:36:03', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-high-speed-super-resolution-imaging-large-field.html'),
(7, 'Researchers improve air pollution exposure models using artificial intelligence and mobility data', 'https://scx1.b-cdn.net/csz/news/tmb/2023/improved-air-pollution.jpg', 'Americans in the Northeast paid greater attention to air quality alerts this summer as wildfire smoke thickened skies with an orange-tinted haze. Smoke and other sources of air pollution contain tiny particles, called fine particulate matter (PM 2.5). Smaller than the width of a human hair, PM 2.5 pose health dangers when inhaled, especially to people with pre-existing heart and lung conditions.', '1', '1', '0', '2023-08-16 18:33:04', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-air-pollution-exposure-artificial-intelligence.html'),
(8, 'A Conductor Who Wants to Put You ‘Inside the Sound’', 'https://static01.nyt.com/images/2023/08/16/multimedia/16PASCAL-02-mwbc/16PASCAL-02-mwbc-moth.jpg', 'Maxime Pascal, a latecomer to classical music, forged an unusual path to the podium that has paid off for him and for audiences.', '1', '1', '0', '2023-08-16 18:30:13', '1,2,4,5', 'The New York Times', 'Joshua Barone', 'entertainment', 'https://www.nytimes.com/2023/08/16/arts/music/maxime-pascal-le-balcon.html'),
(9, 'Authorities to Return Items Seized in Kansas Newspaper Raid', 'https://static01.nyt.com/images/2023/08/16/multimedia/16kansas-paper-1-lhck/16kansas-paper-1-lhck-moth.jpg', 'The raid of the newspaper, The Marion County Record, has drawn condemnation from First Amendment advocates.', '1', '1', '0', '2023-08-16 18:21:31', '1,2,4,5', 'The New York Times', 'Benjamin Mullin and Kevin Draper', 'business', 'https://www.nytimes.com/2023/08/16/business/media/authorities-return-items-kansas-newspaper-raid.html'),
(10, 'Scientists say deepening Arctic snowpack drives greenhouse gas emissions', 'https://scx1.b-cdn.net/csz/news/tmb/2023/scientists-say-deepeni.jpg', 'Human-caused climate change is shortening the snow cover period in the Arctic. But according to new research led by Earth system scientists at the University of California, Irvine, some parts of the Arctic are getting deeper snowpack than normal, and that deep snow is driving the thawing of long-frozen permafrost carbon reserves and leading to increased emissions of greenhouse gases like carbon dioxide and methane.', '1', '1', '0', '2023-08-16 18:17:04', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-scientists-deepening-arctic-snowpack-greenhouse.html'),
(11, 'Michelle Obama reveals the breakfast she ate every day ‘for most of her life’', 'https://static.independent.co.uk/2023/08/16/14/GettyImages-1135975319.jpg?width=1200&auto=webp', '‘I was kind of a picky eater,’ says former first lady', '1', '1', '6', '2023-08-16 18:11:06', '1,2,4,5', 'The Independent - Life and Style', 'Olivia Petter', 'entertainment', 'https://www.independent.co.uk/life-style/food-and-drink/michelle-obama-diet-breakfast-b2394065.html'),
(12, 'Fed Officials Avoided a Victory Lap at July Meeting', 'https://static01.nyt.com/images/2023/08/16/multimedia/16dc-fedminutes-bgcq/16dc-fedminutes-bgcq-moth.jpg', 'Federal Reserve officials raised interest rates at their July 26 meeting, but investors doubt that they will lift them again this year.', '1', '1', '26', '2023-08-16 18:10:23', '1,2,4,5', 'The New York Times', 'Jeanna Smialek', 'business', 'https://www.nytimes.com/2023/08/16/business/economy/federal-reserve-minutes.html'),
(13, 'Surprisingly deadly summer for Lake Tahoe bears: 20 killed, 18 hurt in vehicle collisions', 'https://scx1.b-cdn.net/csz/news/tmb/2022/black-bear.jpg', 'Twenty bears killed and almost 20 more injured—it\'s been a uniquely dangerous summer for Lake Tahoe\'s bear population, with more hit by vehicles from late July to mid-August \"than we\'ve ever had at that time,\" said Ann Bryant of the Bear League.', '1', '1', '0', '2023-08-16 18:10:01', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-deadly-summer-lake-tahoe-vehicle.html'),
(14, 'The Gulf of Mexico is record hot. Here\'s what that means for hurricanes, wildlife', 'https://scx1.b-cdn.net/csz/news/tmb/2019/5-hurricane.jpg', 'Neil Lynch started his Saturday morning like any other: He stopped his car at Belleair Beach, griped about the hourly parking fee and set off on a 5-mile walk.', '1', '1', '0', '2023-08-16 18:10:01', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-gulf-mexico-hot-hurricanes-wildlife.html'),
(15, 'Ukraine defies Russian threat as container ship leaves Odesa', 'https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fd1e00ek4ebabms.cloudfront.net%2Fproduction%2Feb7fa973-e298-4cf9-a563-cde1e56363b2.jpg?source=next-home-page&dpr=2&width=580&fit=scale-down', 'Vessel safely clears Ukrainian waters despite Moscow’s warnings', '1', '1', '0', '2023-08-16 18:08:59', '1,2,4,5', 'Financial Times', NULL, 'business', 'https://www.ft.com/content/3fbb9cc8-3805-4591-9694-5c45cfd8c51b'),
(16, 'In deze voedingsmiddelen zitten de meeste microplastics', 'https://www.telegraaf.nl/images/1200x630/filters:format(jpeg):quality(80)/cdn-kiosk-api.telegraaf.nl/d339ebf0-3b81-11ee-9fcb-02d1dbdc35d1.jpg', 'Lekker en goed eten gaan prima samen, maar toch is de kans groot dat je iedere dag een theelepel plastic naar binnen werkt. Microplastics, om precies te zijn. Om je even goed wakker te schudden: dat is 5 gram per week (het equivalent van een creditcard) en 260 gram per jaar. Dat krijg je dus binnen zonder het te weten. Eet smakelijk.', '1', '1', '0', '2023-08-16 18:02:00', '1,2,4,5', 'De Telegraaf - Lifestyle Overzicht', NULL, 'entertainment', 'https://www.telegraaf.nl/lifestyle/976601604/in-deze-voedingsmiddelen-zitten-de-meeste-microplastics?utm_source=RSS&utm_medium=RSS'),
(17, 'Listen to Pink Floyd\'s \'Another Brick in the Wall,\' as decoded from human brain waves', 'https://cdn.mos.cms.futurecdn.net/7578G864GVNY6bnuVGUUvb.jpg', 'Researchers reconstructed recognizable snippets of the classic Pink Floyd song \"Another Brick in the Wall\" using listeners\' recorded brain activity.', '1', '1', '0', '2023-08-16 18:01:33', '1,2,4,5', 'Live Science: The Most Interesting Articles', NULL, 'science', 'https://www.livescience.com/health/neuroscience/listen-to-pink-floyds-another-brick-in-the-wall-as-decoded-from-human-brain-waves'),
(18, 'Hirota people of Japan intentionally deformed infant skulls 1,800 years ago', 'https://cdn.mos.cms.futurecdn.net/cznKmqxRo8dn6BinsgXhKn.jpg', 'The Hirota people, who occupied a Japanese island for around 400 years, deliberately flattened the back of their children\'s heads. And experts are not entirely sure why.', '1', '1', '0', '2023-08-16 18:01:00', '1,2,4,5', 'Live Science: The Most Interesting Articles', NULL, 'science', 'https://www.livescience.com/archaeology/hirota-people-of-japan-intentionally-deformed-infant-skulls-1800-years-ago'),
(19, 'Atlanta Fed model lifts US third quarter GDP view to 5.8%', 'https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ7F0PQ_L.jpg', 'Atlanta Fed model lifts US third quarter GDP view to 5.8%', '1', '1', '0', '2023-08-16 17:56:07', '1,2,4,5', 'Investing.com | Stock Market Quotes &amp; Financial News', 'Reuters', 'business', 'https://www.investing.com/news/economic-indicators/atlanta-fed-model-lifts-us-third-quarter-gdp-view-to-58-3155812'),
(20, 'OpenAI acquires start-up Global Illumination to work on core products, ChatGPT', 'https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ7F0PS_L.jpg', 'OpenAI acquires start-up Global Illumination to work on core products, ChatGPT', '1', '1', '0', '2023-08-16 17:55:45', '1,2,4,5', 'Investing.com | Stock Market Quotes &amp; Financial News', 'Reuters', 'business', 'https://www.investing.com/news/stock-market-news/openai-acquires-startup-global-illumination-to-work-on-core-products-chatgpt-3155811'),
(21, 'Hoe kon liefdesgeluk Sieneke zo snel verdampen? Pijnlijk gerucht doet de ronde!', 'https://www.telegraaf.nl/images/1200x630/filters:format(jpeg):quality(80)/cdn-kiosk-api.telegraaf.nl/7bf1f500-3c5c-11ee-b72f-0257d57b707f.jpg', 'Ze zouden over drie maanden hun tinnen huwelijk vieren. Maar de handtekening die Sienek en haar echtgenoot Jan tien jaar geleden op hun trouwakte zetten, ’sieren’ binnenkort de scheidingspapieren! Een breuk die in de showbizzwereld uit de lucht komt vallen. Waarom heeft het stel, dat altijd zo hecht leek, de handdoek in de ring gegooid?', '1', '1', '0', '2023-08-16 17:44:00', '1,2,4,5', 'De Telegraaf - Entertainment Overzicht', NULL, 'entertainment', 'https://www.telegraaf.nl/entertainment/1506963358/hoe-kon-liefdesgeluk-sieneke-zo-snel-verdampen-pijnlijk-gerucht-doet-de-ronde?utm_source=RSS&utm_medium=RSS'),
(22, 'Scientists develop artificial metabolic pathway that uses electricity to produce ATP', 'https://scx1.b-cdn.net/csz/news/tmb/2023/understanding-the-elec.jpg', 'When nature performs chemical reactions to create energy-rich compounds from simple molecules, it requires energy. So far, it has not been possible to use human-made electricity to drive these biochemical processes.', '1', '1', '0', '2023-08-16 17:39:03', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-scientists-artificial-metabolic-pathway-electricity.html'),
(23, 'UK arrests part of wider western moves to disrupt Russian spy networks', 'https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fd1e00ek4ebabms.cloudfront.net%2Fproduction%2F7f7be725-89fe-426d-9bfd-d66f746e91a4.jpg?source=next-home-page&dpr=2&width=580&fit=scale-down', 'Investigation under Official Secrets Act against five Bulgarian nationals ongoing', '1', '1', '0', '2023-08-16 17:38:06', '1,2,4,5', 'Financial Times', NULL, 'business', 'https://www.ft.com/content/62670504-b37f-48e7-b493-3ead28986dd4'),
(24, 'Assessing controls on ocean productivity—from space', 'https://scx1.b-cdn.net/csz/news/tmb/2023/assessing-controls-on.jpg', 'Phytoplankton determine how much life the ocean is able to support and play a role in controlling atmospheric carbon dioxide concentrations, thereby regulating our climate. These tiny marine plants depend on sunlight as well as nutrients to thrive—including elements such as iron or nitrogen that can be brought to the ocean surface by currents and upwelling.', '1', '1', '0', '2023-08-16 17:27:08', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-ocean-productivityfrom-space.html'),
(25, 'Study shows how corals and anemones engage in symbiotic relationships with algae and swap nutrients with them', 'https://scx1.b-cdn.net/csz/news/tmb/2023/study-shows-how-corals.jpg', '\"Eat or be eaten\" is not always the way things are in nature. It can be beneficial for different species to team up and pool their capabilities. Cnidarians such as corals and anemones were already committing to this kind of biological joint venture with algae from the dinoflagellate group 250 million years ago.', '1', '1', '0', '2023-08-16 17:26:57', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-corals-anemones-engage-symbiotic-relationships.html'),
(26, 'Exclusive-ArcelorMittal weighs possible bid for US Steel -sources', 'https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ7F0O9_L.jpg', 'Exclusive-ArcelorMittal weighs possible bid for US Steel -sources', '1', '1', '0', '2023-08-16 17:26:16', '1,2,4,5', 'Investing.com | Stock Market Quotes &amp; Financial News', 'Reuters', 'business', 'https://www.investing.com/news/stock-market-news/exclusivearcelormittal-weighs-possible-bid-for-us-steel-sources-3155793'),
(27, '’ArcelorMittal overweegt overname US Steel’', 'https://www.telegraaf.nl/images/1200x630/filters:format(jpeg):quality(80)/cdn-kiosk-api.telegraaf.nl/5091e2fa-3c5a-11ee-a763-0218eaf05005.jpg', 'Staalmaker ArcelorMittal doet een bod op de Amerikaanse concurrent US Steel. De grootste producent van Europa bespreekt een mogelijke overname met zijn investeringsbankiers, aldus bronnen tegen Reuters.', '1', '1', '0', '2023-08-16 17:25:42', '1,2,4,5', 'De Telegraaf - Financieel Overzicht', NULL, 'business', 'https://www.telegraaf.nl/financieel/1908677149/arcelor-mittal-overweegt-overname-us-steel?utm_source=RSS&utm_medium=RSS'),
(28, 'Online outrage can benefit brands that take stances on social issues', 'https://scx1.b-cdn.net/csz/news/tmb/2023/online-outrage-can-ben.jpg', 'Nike\'s advertisement featuring Colin Kaepernick sparked a social media firestorm in 2018. Kaepernick, a former San Francisco 49ers quarterback, first made headlines in 2016 when he protested against police brutality by kneeling during the American national anthem.', '1', '1', '0', '2023-08-16 17:20:01', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-online-outrage-benefit-brands-stances.html'),
(29, 'Novel enzyme could boost sustainable production of aviation fuel', 'https://scx1.b-cdn.net/csz/news/tmb/2023/novel-enzyme-could-boo.jpg', 'In recent decades, scientists have sought solutions to improve the sustainable production of biofuels from renewable sources. The latest advance in this field was announced at the end of May by Brazilian researchers and could boost the production of sustainable biofuels for aviation and maritime shipping.', '1', '1', '0', '2023-08-16 17:18:10', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-enzyme-boost-sustainable-production-aviation.html'),
(30, 'Study shows bacterial viruses \'glue\' RNA to host proteins', 'https://scx1.b-cdn.net/csz/news/tmb/2023/viruses-glue-rna-to-pr.jpg', 'Until now, RNA and proteins were thought to interact only briefly during cellular processes. Researchers at the Max Planck Institute for Terrestrial Microbiology in Marburg, Germany, have discovered that this is not the case. During their developmental cycle, bacterial viruses \"glue\" specific RNAs to host proteins. As the authors describe in their publication in the journal Nature, \"RNAylation\" could open up new avenues for phage therapy or drug development.', '1', '1', '0', '2023-08-16 17:18:03', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-bacterial-viruses-rna-host-proteins.html'),
(31, 'NASA\'s lunar trailblazer gets final payload for moon water hunt', 'https://scx1.b-cdn.net/csz/news/tmb/2023/nasas-lunar-trailblaze.jpg', 'NASA\'s Lunar Trailblazer is nearing completion now that its second and final cutting-edge science instrument has been added to the small spacecraft. Built by the University of Oxford in England and contributed by the UK Space Agency, the Lunar Thermal Mapper (LTM) joins the High-resolution Volatiles and Minerals Moon Mapper (HVM3), which was integrated with the spacecraft late last year. Together, the instruments will enable scientists to determine the abundance, location, and form of the moon\'s water.', '1', '1', '0', '2023-08-16 17:12:04', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-nasa-lunar-trailblazer-payload-moon.html'),
(32, 'Texas approves plan to mandate Tesla tech for EV chargers despite opposition', 'https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ7F0N8_L.jpg', 'Texas approves plan to mandate Tesla tech for EV chargers despite opposition', '1', '1', '0', '2023-08-16 17:03:07', '1,2,4,5', 'Investing.com | Stock Market Quotes &amp; Financial News', 'Reuters', 'business', 'https://www.investing.com/news/economy/texas-approves-plan-to-mandate-tesla-tech-for-ev-chargers-despite-opposition-3155639'),
(33, 'Maui tourism, an economic mainstay, sparks anger amid fire ruin', 'https://i-invdn-com.investing.com/trkd-images/LYNXMPEJ7F0BT_L.jpg', 'Maui tourism, an economic mainstay, sparks anger amid fire ruin', '1', '1', '0', '2023-08-16 17:02:34', '1,2,4,5', 'Investing.com | Stock Market Quotes &amp; Financial News', 'Reuters', 'business', 'https://www.investing.com/news/economy/maui-tourism-an-economic-mainstay-sparks-anger-amid-fire-ruin-3155212'),
(34, 'Hummingbird beak points the way to future micro machine design', 'https://scx1.b-cdn.net/csz/news/tmb/2023/hummingbird-beak-point.jpg', 'A Cornell research team has developed a new way to design complex microscale machines, one that draws inspiration from the operation of proteins and hummingbird beaks.', '1', '1', '0', '2023-08-16 17:01:33', '1,2,4,5', 'Phys.org - News And Articles On Science And Technology', NULL, 'science', 'https://phys.org/news/2023-08-hummingbird-beak-future-micro-machine.html'),
(35, 'YouTube\'s NFL Sunday Ticket includes live chat and highlights in Shorts', 'https://s.yimg.com/os/creatr-uploaded-images/2023-05/feba4ca0-fa60-11ed-bf9e-c7f496f7a6d5', 'Who&#39;s ready for some (bad opinions from the internet while you watch) football? YouTube has revealed some more NFL Sunday Ticket features for the upcoming season. As you watch games, you&#39;ll be able to view a live chat and read what other people think about a certain play or call. Live chat and polls will be available on both mobile and TVs.YouTube users will be able to watch real-time NFL highlights on Shorts. On Sunday afternoons, these highlights will include a red Live ring around the channel&#39;s avatar, and clicking on this will take users to the NFL channel&#39;s Live tab. There...', '1', '1', '0', '2023-08-16 17:00:37', '1,2,4,5', 'Engadget', 'Kris Holt', 'technology', 'https://www.engadget.com/youtubes-nfl-sunday-ticket-includes-live-chat-and-highlights-in-shorts-170037161.html?src=rss'),
(36, 'Coinbase secures approval to offer crypto futures to US retail investors', 'https://www.ft.com/__origami/service/image/v2/images/raw/https%3A%2F%2Fd1e00ek4ebabms.cloudfront.net%2Fproduction%2Fa1bd85ad-f4d8-433d-9a1c-d2553f4e3c24.jpg?source=next-home-page&dpr=2&width=580&fit=scale-down', 'Green light from NFA marks rare regulatory victory for cryptocurrency exchange', '1', '1', '0', '2023-08-16 16:57:15', '1,2,4,5', 'Financial Times', NULL, 'business', 'https://www.ft.com/content/48759411-fdd9-42a9-847e-5160c351376c');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `tbl_article`
--
ALTER TABLE `tbl_article`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `tbl_article`
--
ALTER TABLE `tbl_article`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
